package com.frostvoid.wpMerchant.services

import akka.actor.{Actor, ActorLogging}
import com.frostvoid.wpMerchant.api._
import com.frostvoid.wpMerchant.util.IdGenerator

/**
  * Handles retrieval and storage of Items in a mutable map
  */
class ItemWorker extends Actor with ActorLogging with IdGenerator {

  private val itemStore = collection.mutable.Map.empty[Int, Item] // Int = Item.id

  override def receive: Receive = {
    case GetItemRequest(id) => sender() ! itemStore.get(id).fold(ItemNotFound: ItemReply)(i => ItemReturned(i))
    case AddItemRequest(name, description) => sender() ! addItem(name, description)
  }

  override def postStop: Unit = log.info("Shutting down")

  override def preStart: Unit = log.info("Starting up")

  private def addItem(name: String, description: String): ItemReply = {
    val id = generateId
    log.info(s"Adding item named '$name', autogenerated id is '$id'")
    if (itemStore.contains(id)) {
      log.warning(s"Autogenerated ID collision, trying to add item with name '$name' to item store with id $id")
      ItemNotCreated
    }
    else {
      val i = Item(id, name, description)
      itemStore.put(id, i)
      ItemReturned(i)
    }
  }
}


