package com.frostvoid.wpMerchant.services

import akka.actor.{Actor, ActorLogging, Props}
import com.frostvoid.wpMerchant.api._
import com.frostvoid.wpMerchant.util.IdGenerator

/**
  * Handles retrieval and storage of Merchants in a mutable map
  */
class MerchantWorker extends Actor with ActorLogging with IdGenerator {

  private val merchantStore = collection.mutable.Map.empty[Int, Merchant] // Int = Merchant.id

  override def receive: Receive = {
    case GetMerchantRequest(id) => sender() ! merchantStore.get(id).fold(MerchantNotFound: MerchantReply)(m => MerchantReturned(m))
    case AddMerchantRequest(name) => sender() ! addMerchant(name)
  }

  override def postStop: Unit = log.info("Shutting down")

  override def preStart: Unit = log.info("Starting up")

  private def addMerchant(name: String): MerchantReply = {
    val id = generateId
    log.info(s"Adding merchant named '$name', autogenerated id is '$id'")
    if (merchantStore.contains(id)) {
      log.warning(s"Autogenerated ID collision, trying to add merchant $name to merchant store with id $id")
      MerchantNotCreated
    }
    else {
      val m = Merchant(id, name)
      merchantStore.put(id, m)
      MerchantReturned(m)
    }
  }
}