package com.frostvoid.wpMerchant.services

import akka.actor.{Actor, ActorLogging, Props}
import com.frostvoid.wpMerchant.api._
import com.frostvoid.wpMerchant.util.IdGenerator

/**
  * @author eaakre - 2018-03-14
  */
class MerchantWorker extends Actor with ActorLogging with IdGenerator  {

  private val merchantStore = collection.mutable.Map.empty[Int, Merchant]

  override def receive: Receive = {
    case GetMerchantRequest(id) => sender() ! merchantStore.get(id).fold(EmptyReply: MerchantReply)(m => MerchantReturned(m))
    case AddMerchantRequest(name) => sender() ! addMerchant(name)
  }

  private def addMerchant(name: String): MerchantReply = {
    val id = generateId
    log.info(s"Adding merchant named '$name', autogenerated id is '$id'")
    if(merchantStore.contains(id)) {
      log.warning(s"Autogenerated ID collision, trying to add merchant $name to merchant store with id $id")
      EmptyReply
    }
    else {
      val m = Merchant(id, name)
      merchantStore.put(id, m)
      MerchantReturned(m)
    }
  }
}

object MerchantWorker {
  def props(): Props = Props(new MerchantWorker)
}
